config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  devise_for :users

  resources :politicians do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  resources :users do
    resources :avatars
  end

  get 'pages/about'

  get 'pages/contact'

  root 'politicians#index'

end

app/models/politician.rb
class Politician < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  searchkick

  has_many :reviews
  belongs_to :user

  validates :first_name, :last_name, :wikipage, :image, presence: true
  validates :wikipage, format: { with: /\Ahttps?:\/\/.*\z/,
    message: "must start with http:// or https://" }

  def avg_rating
    @reviews = Review.where(politician_id: self.id)
    if @reviews.blank?
      0
    else
      @reviews.average(:rating).round(2)
    end
  end

  def name
    first_name + " " + last_name
  end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  before_action :set_politician, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search, :index, :show]
  before_action :check_user, except: [:search, :index, :show, :new, :create, :destroy]

  # GET /politicians
  # GET /politicians.json

  def search
    if params[:search].present?
      @politicians = Politician.search(params[:search])
    else
      @politicians = Politician.all
    end
  end


  def index
    @politicians = Politician.all
  end

  def show
    @reviews = Review.where(politician_id: @politician.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  def new
    @politician = Politician.new
  end

  def edit
  end

  def create
    @politician = Politician.new(politician_params)
    @politician.user_id = current_user.id

    respond_to do |format|
      if @politician.save
        format.html { redirect_to @politician, notice: 'Politician was successfully created.' }
        format.json { render :show, status: :created, location: @politician }
      else
        format.html { render :new }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @politician.update(politician_params)
        format.html { redirect_to @politician, notice: 'Politician profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @politician }
      else
        format.html { render :edit }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politicians/1
  # DELETE /politicians/1.json
  def destroy
    @politician.destroy
    respond_to do |format|
      format.html { redirect_to politicians_url, notice: 'The Politician was successfully destroyed. Booo!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politician
      @politician = Politician.find(params[:id])
    end

    def check_user
      unless current_user.admin?
          redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def politician_params
      params.require(:politician).permit(:first_name, :last_name, :party, :occupation, :country, :area, :wikipage, :image)
    end
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/views/politicians/_form.html.erb
<div class="marginall">
  <%= form_for(@politician) do |f| %>
    <% if @politician.errors.any? %>
      <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4><%= pluralize(@politician.errors.count, "error") %> prohibited this politician from being saved:</h4>

        <ul>
        <% @politician.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name, class: "form-control", placeholder: "Sadiq" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name, class: "form-control", placeholder: "Khan" %>
    </div>
    <div class="form-group">
      <%= f.label :party %><br>
      <%= f.text_field :party, class: "form-control", placeholder: "Labour Party" %>
    </div>
    <div class="form-group">
      <%= f.label :occupation %><br>
      <%= f.text_field :occupation, class: "form-control", placeholder: "City Mayor" %>
    </div>
    <div class="form-group">
      <%= f.label :country %><br>
      <%= f.country_select :country, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :area %><br>
      <%= f.text_field :area, class: "form-control", placeholder: "London" %>
    </div>
    <div class="form-group">
      <%= f.label :wikipage %><br>
      <%= f.text_field :wikipage, class: "form-control", placeholder: "https://en.wikipedia.org/wiki/Sadiq_Khan" %>
    </div>
    <div class="form-group">
     <%= f.label :image %><br>
     <%= f.file_field :image, class: "form-control" %>
   </div>
    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/politicians/edit.html.erb
<div class="marginall">
  <h1 style="text-align: center">Editing Politician</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @politician, class: "btn btn-link" %> |
  <%= link_to 'Back', politicians_path, class: "btn btn-link" %>
</div>

app/views/politicians/index.html.erb
<div class="jumbotron">
  <div class="container-fluid">
    <h1>DigGov is a Platform Where You Can Share Your Political Opinion</h1>
    <h2>Review Your Politicians' Work Performance!</h2>
    <h2>Read What Others Say About Them Too!</h2>
  </div>
</div>

<div>
  <h1 class="bar"><span style="text-decoration: line-through; font-size: 26px;">The Most Hated Politicians</span>  Recent Posts</h1>

  <div class="center">
    <div class="row">
      <% @politicians.each do |politician| %>
        <div class="col-xs-6 col-md-3">
          <div class="icon">
            <div class="img-thumbnail">
              <%= link_to image_tag(politician.image_url), politician, class: "img-responsive aspect" %>
              <div class="caption">
                <h3><%= link_to politician.first_name + " " + politician.last_name, politician %></h3>
                <div class="star-rating" data-score= <%= politician.avg_rating %> ></div>
                <h4><%= politician.party %></h4>
                <h4><%= politician.occupation %></h4>
                <h4><%= politician.country %></h4>
                <h4><%= politician.area %></h4>
                  <% if user_signed_in? && current_user.admin? %>
                    <td><%= link_to 'Edit', edit_politician_path(politician), class: "btn btn-link" %></td>
                    <td><%= link_to 'Destroy', politician, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/yelpdemo/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/politicians/new.html.erb
<div class="marginall">
  <h1 style="text-align: center">New Politician</h1>

  <%= render 'form' %>
  <%= link_to 'Back', politicians_path, class: "btn btn-link" %>
</div>

app/views/politicians/search.html.erb
<div class="marginall">
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Party</th>
        <th>Occupation</th>
        <th>Country</th>
        <th>Area</th>
        <th>Wikipage</th>
        <% if user_signed_in? && current_user.admin? %>
          <th colspan="2"></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @politicians.each do |politician| %>
        <tr>
          <td><%= link_to politician.first_name, politician %></td>
          <td><%= link_to politician.last_name, politician %></td>
          <td><%= politician.party %></td>
          <td><%= politician.occupation %></td>
          <td><%= politician.country %></td>
          <td><%= politician.area %></td>
          <td><%= link_to politician.wikipage, politician.wikipage %></td>
          <% if user_signed_in? && current_user.admin? %>
            <td><%= link_to 'Edit', edit_politician_path(politician), class: "btn btn-link" %></td>
            <td><%= link_to 'Destroy', politician, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/politicians/show.html.erb
<div class="marginall">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @politician.image_url %>

      <h2 class="name">
        <%= @politician.first_name %>
      </h2>

      <h2 class="name">
        <%= @politician.last_name %>
      </h2>

      <div class="star-rating" data-score= <%= @avg_rating %> ></div>
      </br>
      <p>(<%= "#{@reviews.length} reviews" %>)</p>

      <p class="font">
        <strong>Party:</strong>
        <div class="details">
          <%= @politician.party %>
        </div>
      </p>

      <p class="font">
        <strong>Occupation:</strong>
        <div class="details">
          <%= @politician.occupation %>
        </div>
      </p>

      <p class="font">
        <strong>Country:</strong>
        <div class="details">
          <%= @politician.country %>
        </div>
      </p>

      <p class="font">
        <strong>Area:</strong>
        <div class="details">
          <%= @politician.area %>
        </div>
      </p>

      <p class="font">
          <strong><%= link_to "Wikipage", @politician.wikipage, :target => "_blank" %></strong>
      </p>

      </br>
      </br>
      <%= link_to "Write a Review", new_politician_review_path(@politician), class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_politician_path(@politician), class: "btn btn-link" %> |
      <%= link_to 'Back', politicians_path, class: "btn btn-link" %>

    </div>

    <div class="col-md-8">
      <% if @reviews.blank? %>
        <h3 class="no-review">No reviews yet. Be the first to write one!</h3>
      <% else %>
        <table class="table">
          <thead>
            <tr>
              <th class="col-md-3"></th>
              <th class="col-md-9"></th>
            </tr>
          </thead>

          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td>
                  <h4>
                    <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize}" %>
                  </h4>
                  <p><%= review.created_at.strftime("%B %d, %Y") %></p>
                </td>

                <td>
                  <div class="star-rating" data-score= <%= review.rating %> ></div>
                  <br />
                  <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>

                  <% if user_signed_in? %>
                    <% if (review.user == current_user) || (current_user.admin?) %>
                      <%= link_to "Edit", edit_politician_review_path(@politician, review) %> |
                      <%= link_to "Delete", politician_review_path(@politician, review), method: :delete %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>

  <script>
    $('.star-rating').raty({
      path: 'https://s3.amazonaws.com/yelpdemo/stars',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      }
    });
  </script>
</div>