config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  devise_for :users

  resources :politicians do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  resources :users do
    resources :avatars
  end

  get 'pages/about'

  get 'pages/contact'

  root 'politicians#index'

end

app/helpers/layout_helper.rb
module LayoutHelper
  def copyright_notice_year_range(start_year)
    # In case the input was not a number (nil.to_i will return a 0)
    start_year = start_year.to_i

    # Get the current year from the system
    current_year = Time.new.year

    # When the current year is more recent than the start year, return a string
    # of a range (e.g., 2010 - 2012). Alternatively, as long as the start year
    # is reasonable, return it as a string. Otherwise, return the current year
    # from the system.
    if current_year > start_year && start_year > 2015
      "#{start_year} - #{current_year}"
    elsif start_year > 2015
      "#{start_year}"
    else
      "#{current_year}"
    end
  end
end

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JQuery -->
<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
  <footer class="footer">
  &copy; <%= copyright_notice_year_range(2015) %> <%= link_to "DigGov", pages_about_path %>  All Rights Reserved.
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to root_path do %>
        <img class="logo" alt="DigGov" src="http://s32.postimg.org/sadhnst39/logo.png" width="50" height="50">
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" style="margin: 1em"id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>

      <%= form_tag search_politicians_path, method: :get, class: "navbar-form navbar-left" do %>
          <p>
            <%= text_field_tag :search, params[:search], class: "form-control" %>
            <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
          </p>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" aria-label="Account">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          </button>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to "My Dashboard", user_path(current_user) %></li>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>
          </ul>
        </div>
        <%= link_to 'List New Politician', new_politician_path, :class => "btn btn-warning navbar-btn" %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DigGov - Digital Governance</title>
  <%= render 'layouts/bootstrap' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Chivo' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container-fluid">

    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>